// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShowVault.Api.Data;

#nullable disable

namespace ShowVault.Api.Data.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260809211327_AddBirdDogIdentificationResults")]
    partial class AddBirdDogIdentificationResults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShowVault.Platform.Agents.AgentEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBySubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SecretHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SecretHash")
                        .IsUnique();

                    b.HasIndex("VenueId");

                    b.ToTable("agent_enrollments", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.IssuedAgentCommand", b =>
                {
                    b.Property<Guid>("CommandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("CommandId");

                    b.HasIndex("AgentId", "Status", "IssuedAt");

                    b.ToTable("issued_agent_commands", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.ReceivedAgentEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("EventId");

                    b.HasIndex("AgentId", "ReceivedAt");

                    b.ToTable("received_agent_events", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.RecoveryCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CandidateType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBySubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PluginId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ValidationCommandId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ValidationFileCount")
                        .HasColumnType("integer");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValidationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool?>("ValidationTruncated")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ValidationCommandId")
                        .IsUnique();

                    b.HasIndex("AgentId", "DetectedAt");

                    b.ToTable("recovery_candidates", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.SubnetProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<int?>("BirdDogIdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BirdDogIdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("BirdDogIdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BirdDogIdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("BirdDogIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BirdDogIdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("BirdDogIdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("BlackmagicVideohubIdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BlackmagicVideohubIdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("BlackmagicVideohubIdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BlackmagicVideohubIdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("BlackmagicVideohubIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("BlackmagicVideohubIdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("BlackmagicVideohubIdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBySubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DiscoveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DiscoveryCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("DiscoveryMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DiscoveryStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("FallbackTargetCount")
                        .HasColumnType("integer");

                    b.Property<int?>("GrandMa2IdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GrandMa2IdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("GrandMa2IdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GrandMa2IdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("GrandMa2IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GrandMa2IdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("GrandMa2IdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("IdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("IdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("IdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("IdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("IdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("IdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("InterfaceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("NewTekTriCasterIdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NewTekTriCasterIdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewTekTriCasterIdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NewTekTriCasterIdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("NewTekTriCasterIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NewTekTriCasterIdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("NewTekTriCasterIdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("PassiveCandidateCount")
                        .HasColumnType("integer");

                    b.Property<int>("PrefixLength")
                        .HasColumnType("integer");

                    b.Property<int?>("RespondingHostCount")
                        .HasColumnType("integer");

                    b.Property<int?>("YamahaIdentificationAttemptedHostCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("YamahaIdentificationCommandId")
                        .HasColumnType("uuid");

                    b.Property<string>("YamahaIdentificationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("YamahaIdentificationStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("YamahaIdentifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("YamahaIdentifiedHostCount")
                        .HasColumnType("integer");

                    b.Property<string>("YamahaIdentifiedProductFamilies")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BirdDogIdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("BlackmagicVideohubIdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("DiscoveryCommandId")
                        .IsUnique();

                    b.HasIndex("GrandMa2IdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("IdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("NewTekTriCasterIdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("YamahaIdentificationCommandId")
                        .IsUnique();

                    b.HasIndex("AgentId", "DetectedAt");

                    b.ToTable("subnet_proposals", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.VenueAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("CredentialHash")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CredentialRotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("venue_agents", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Organizations.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "IdentitySubject")
                        .IsUnique();

                    b.ToTable("memberships", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Venues.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name");

                    b.ToTable("venues", (string)null);
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.AgentEnrollment", b =>
                {
                    b.HasOne("ShowVault.Platform.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.IssuedAgentCommand", b =>
                {
                    b.HasOne("ShowVault.Platform.Agents.VenueAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.ReceivedAgentEvent", b =>
                {
                    b.HasOne("ShowVault.Platform.Agents.VenueAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.RecoveryCandidate", b =>
                {
                    b.HasOne("ShowVault.Platform.Agents.VenueAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.SubnetProposal", b =>
                {
                    b.HasOne("ShowVault.Platform.Agents.VenueAgent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Agents.VenueAgent", b =>
                {
                    b.HasOne("ShowVault.Platform.Venues.Venue", null)
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Organizations.Membership", b =>
                {
                    b.HasOne("ShowVault.Platform.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShowVault.Platform.Venues.Venue", b =>
                {
                    b.HasOne("ShowVault.Platform.Organizations.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
